name: Run Tests

on:
  push: # Run tests on every push
  pull_request: # Run tests when a pull request is created or updated

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4'] # Define the different PHP versions to test with

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP with the matrix version
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }} # Use the PHP version defined in the matrix
          coverage: none

      # Install dependencies
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Run PHPUnit tests
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml
